var searchData=
[
  ['calculation_0',['Frequency Calculation',['../md_docs_2configuration.html#autotoc_md33',1,'']]],
  ['call_20setpwmfreq_20before_20setting_20channels_1',['Q: Why do I need to call SetPwmFreq() before setting channels?',['../md_docs_2troubleshooting.html#autotoc_md142',1,'']]],
  ['can_20i_20change_20frequency_20after_20setting_20channels_2',['Q: Can I change frequency after setting channels?',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['can_20i_20use_20multiple_20pca9685_20devices_3',['Q: Can I use multiple PCA9685 devices?',['../md_docs_2troubleshooting.html#autotoc_md145',1,'']]],
  ['chain_4',['Multiple PCA9685 Devices (Daisy Chain)',['../md_docs_2hardware__setup.html#autotoc_md74',1,'']]],
  ['change_20frequency_20after_20setting_20channels_5',['Q: Can I change frequency after setting channels?',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['channel_20configuration_6',['Channel Configuration',['../md_docs_2configuration.html#autotoc_md35',1,'']]],
  ['channel_20control_7',['Channel Control',['../md_docs_2configuration.html#autotoc_md37',1,'Bulk Channel Control'],['../md_docs_2configuration.html#autotoc_md36',1,'Individual Channel Control']]],
  ['channel_20out_20of_20range_8',['Error: Channel Out of Range',['../md_docs_2troubleshooting.html#autotoc_md136',1,'']]],
  ['channel_20update_9',['Example 5: Bulk Channel Update',['../md_docs_2examples.html#autotoc_md56',1,'']]],
  ['channels_10',['Channels',['../md_docs_2examples.html#autotoc_md54',1,'Example 3: Multiple Channels'],['../md_docs_2troubleshooting.html#autotoc_md139',1,'No Output on Channels'],['../md_docs_2hardware__setup.html#autotoc_md66',1,'Output Channels'],['../md_docs_2troubleshooting.html#autotoc_md143',1,'Q: Can I change frequency after setting channels?'],['../md_docs_2troubleshooting.html#autotoc_md142',1,'Q: Why do I need to call SetPwmFreq() before setting channels?'],['../md_docs_2quickstart.html#autotoc_md129',1,'Step 6: Control Channels']]],
  ['class_11',['Class',['../md_docs_2api__reference.html#autotoc_md13',1,'Core Class'],['../md_docs_2platform__integration.html#autotoc_md107',1,'Step 1: Create Your Implementation Class']]],
  ['clone_12',['Option 1: Git Clone',['../md_docs_2installation.html#autotoc_md88',1,'']]],
  ['cmake_13',['Using CMake',['../md_docs_2installation.html#autotoc_md92',1,'']]],
  ['code_14',['Source Code',['../md_docs_2api__reference.html#autotoc_md12',1,'']]],
  ['common_20error_20messages_15',['Common Error Messages',['../md_docs_2troubleshooting.html#autotoc_md134',1,'']]],
  ['common_20frequencies_16',['Common Frequencies',['../md_docs_2configuration.html#autotoc_md34',1,'']]],
  ['common_20pitfalls_17',['Common Pitfalls',['../md_docs_2platform__integration.html#autotoc_md112',1,'']]],
  ['comparison_18',['Performance Comparison',['../md_docs_2platform__integration.html#autotoc_md104',1,'']]],
  ['compile_20time_20polymorphism_20strong_19',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md100',1,'']]],
  ['configuration_20',['Configuration',['../md_docs_2hardware__setup.html#autotoc_md69',1,'Address Configuration'],['../md_docs_2configuration.html#autotoc_md35',1,'Channel Configuration'],['../md_docs_2configuration.html',1,'Configuration'],['../md_docs_2api__reference.html#autotoc_md22',1,'Configuration'],['../md_docs_2configuration.html#autotoc_md30',1,'I2C Address Configuration'],['../md_docs_2hardware__setup.html#autotoc_md70',1,'I2C Bus Configuration'],['../md_docs_2hardware__setup.html#autotoc_md68',1,'I2C Configuration'],['../md_docs_2api__reference.html#autotoc_md20',1,'Output Configuration'],['../md_docs_2configuration.html#autotoc_md31',1,'PWM Frequency Configuration'],['../md_docs_2configuration.html#autotoc_md43',1,'Runtime Configuration']]],
  ['configuration_2emd_21',['configuration.md',['../configuration_8md.html',1,'']]],
  ['confusion_22',['❌ Address Format Confusion',['../md_docs_2platform__integration.html#autotoc_md117',1,'']]],
  ['connections_23',['Connections',['../md_docs_2hardware__setup.html#autotoc_md64',1,'Basic I2C Connections'],['../md_docs_2hardware__setup.html#autotoc_md63',1,'Pin Connections']]],
  ['constants_24',['Constants',['../md_docs_2api__reference.html#autotoc_md26',1,'']]],
  ['contents_25',['📚 Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['contributing_26',['🤝 Contributing',['../index.html#autotoc_md9',1,'']]],
  ['control_27',['Control',['../md_docs_2configuration.html#autotoc_md37',1,'Bulk Channel Control'],['../md_docs_2examples.html#autotoc_md51',1,'Example 1: Basic Servo Control'],['../md_docs_2configuration.html#autotoc_md48',1,'For Motor Control'],['../md_docs_2configuration.html#autotoc_md46',1,'For Servo Control'],['../md_docs_2api__reference.html#autotoc_md17',1,'Frequency Control'],['../md_docs_2configuration.html#autotoc_md36',1,'Individual Channel Control'],['../md_docs_2api__reference.html#autotoc_md18',1,'PWM Control']]],
  ['control_20channels_28',['Step 6: Control Channels',['../md_docs_2quickstart.html#autotoc_md129',1,'']]],
  ['control_20the_20oe_20output_20enable_20pin_29',['Q: How do I control the OE (Output Enable) pin?',['../md_docs_2troubleshooting.html#autotoc_md147',1,'']]],
  ['copy_20files_30',['Option 2: Copy Files',['../md_docs_2installation.html#autotoc_md89',1,'']]],
  ['core_20class_31',['Core Class',['../md_docs_2api__reference.html#autotoc_md13',1,'']]],
  ['correct_20crtp_20implementation_32',['✅ Correct CRTP Implementation',['../md_docs_2platform__integration.html#autotoc_md114',1,'']]],
  ['correct_20template_20parameter_33',['✅ Correct Template Parameter',['../md_docs_2platform__integration.html#autotoc_md116',1,'']]],
  ['create_20driver_20instance_34',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md126',1,'']]],
  ['create_20your_20implementation_20class_35',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md107',1,'']]],
  ['crtp_36',['&lt;tt&gt;I2cInterface\&lt;Derived\&gt;&lt;/tt&gt; (CRTP)',['../md_docs_2api__reference.html#autotoc_md28',1,'']]],
  ['crtp_20curiously_20recurring_20template_20pattern_37',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md97',1,'']]],
  ['crtp_20implementation_38',['✅ Correct CRTP Implementation',['../md_docs_2platform__integration.html#autotoc_md114',1,'']]],
  ['crtp_20instead_20of_20virtual_20functions_39',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md98',1,'']]],
  ['crtp_20works_40',['How CRTP Works',['../md_docs_2platform__integration.html#autotoc_md103',1,'']]],
  ['curiously_20recurring_20template_20pattern_41',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md97',1,'']]]
];
