var searchData=
[
  ['t_20forget_20the_20template_20parameter_0',['❌ Don&apos;t Forget the Template Parameter',['../md_docs_2platform__integration.html#autotoc_md122',1,'']]],
  ['t_20use_20virtual_20functions_1',['❌ Don&apos;t Use Virtual Functions',['../md_docs_2platform__integration.html#autotoc_md120',1,'']]],
  ['table_20of_20contents_2',['📚 Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['template_20parameter_3',['Template Parameter',['../md_docs_2platform__integration.html#autotoc_md123',1,'✅ Correct Template Parameter'],['../md_docs_2platform__integration.html#autotoc_md122',1,'❌ Don&apos;t Forget the Template Parameter']]],
  ['template_20pattern_4',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md104',1,'']]],
  ['testing_20your_20implementation_5',['Testing Your Implementation',['../md_docs_2platform__integration.html#autotoc_md125',1,'']]],
  ['the_20component_6',['The Component',['../md_docs_2cmake__integration.html#autotoc_md31',1,'1. Reference the Component'],['../md_docs_2cmake__integration.html#autotoc_md33',1,'3. Require the Component']]],
  ['the_20difference_20between_20setpwm_20and_20setduty_7',['Q: What&apos;s the difference between SetPwm() and SetDuty()?',['../md_docs_2troubleshooting.html#autotoc_md151',1,'']]],
  ['the_20driver_20root_20if_20needed_8',['2. Override the Driver Root (if needed)',['../md_docs_2cmake__integration.html#autotoc_md32',1,'']]],
  ['the_20examples_9',['Running the Examples',['../md_docs_2examples.html#autotoc_md65',1,'']]],
  ['the_20header_10',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md131',1,'']]],
  ['the_20i2c_20interface_11',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['the_20library_12',['Building the Library',['../md_docs_2installation.html#autotoc_md97',1,'']]],
  ['the_20oe_20output_20enable_20pin_13',['Q: How do I control the OE (Output Enable) pin?',['../md_docs_2troubleshooting.html#autotoc_md154',1,'']]],
  ['the_20source_14',['Obtaining the Source',['../md_docs_2installation.html#autotoc_md94',1,'']]],
  ['the_20template_20parameter_15',['❌ Don&apos;t Forget the Template Parameter',['../md_docs_2platform__integration.html#autotoc_md122',1,'']]],
  ['time_20polymorphism_20strong_16',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md107',1,'']]],
  ['to_20call_20setpwmfreq_20before_20setting_20channels_17',['Q: Why do I need to call SetPwmFreq() before setting channels?',['../md_docs_2troubleshooting.html#autotoc_md149',1,'']]],
  ['troubleshooting_18',['Troubleshooting',['../md_docs_2troubleshooting.html',1,'Troubleshooting'],['../md_docs_2quickstart.html#autotoc_md138',1,'Troubleshooting']]],
  ['troubleshooting_20strong_19',['&lt;strong&gt;Troubleshooting&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md90',1,'']]],
  ['troubleshooting_2emd_20',['troubleshooting.md',['../troubleshooting_8md.html',1,'']]],
  ['tt_20i2cinterface_20derived_20tt_20crtp_21',['&lt;tt&gt;I2cInterface\&lt;Derived\&gt;&lt;/tt&gt; (CRTP)',['../md_docs_2api__reference.html#autotoc_md28',1,'']]],
  ['tt_20pca9685_20i2ctype_20tt_22',['&lt;tt&gt;PCA9685\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md14',1,'']]],
  ['tt_20reset_20tt_20returns_20false_23',['Error: Initialization Fails (&lt;tt&gt;Reset()&lt;/tt&gt; returns false)',['../md_docs_2troubleshooting.html#autotoc_md142',1,'']]],
  ['type_20aliases_24',['Type Aliases',['../md_docs_2api__reference.html#autotoc_md24',1,'']]],
  ['type_20safety_25',['4. **Type Safety**',['../md_docs_2platform__integration.html#autotoc_md109',1,'']]],
  ['types_26',['Types',['../md_docs_2api__reference.html#autotoc_md23',1,'']]]
];
