var searchData=
[
  ['efficiency_20strong_0',['3. &lt;strong&gt;Memory Efficiency&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['enable_20oe_20pin_1',['Enable OE Pin',['../md_docs_2configuration.html#autotoc_md47',1,'Output Enable (OE) Pin'],['../md_docs_2hardware__setup.html#autotoc_md82',1,'Output Enable (OE) Pin']]],
  ['enable_20pin_2',['Q: How do I control the OE (Output Enable) pin?',['../md_docs_2troubleshooting.html#autotoc_md154',1,'']]],
  ['enumerations_3',['Enumerations',['../md_docs_2api__reference.html#autotoc_md25',1,'']]],
  ['error_20handling_4',['Error Handling',['../md_docs_2api__reference.html#autotoc_md21',1,'']]],
  ['error_20messages_5',['Common Error Messages',['../md_docs_2troubleshooting.html#autotoc_md141',1,'']]],
  ['error_3a_20channel_20out_20of_20range_6',['Error: Channel Out of Range',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['error_3a_20initialization_20fails_20tt_20reset_20tt_20returns_20false_7',['Error: Initialization Fails (&lt;tt&gt;Reset()&lt;/tt&gt; returns false)',['../md_docs_2troubleshooting.html#autotoc_md142',1,'']]],
  ['errors_8',['Runtime Errors',['../md_docs_2troubleshooting.html#autotoc_md147',1,'']]],
  ['esp_20idf_9',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md116',1,'']]],
  ['esp_20idf_20esp32_20examples_10',['Using ESP-IDF (ESP32 Examples)',['../md_docs_2installation.html#autotoc_md100',1,'']]],
  ['esp_20idf_20integration_11',['ESP-IDF Integration',['../md_docs_2cmake__integration.html#autotoc_md30',1,'']]],
  ['esp32_20applications_12',['ESP32 Applications',['../md_docs_2examples.html#autotoc_md66',1,'']]],
  ['esp32_20applications_20strong_13',['&lt;strong&gt;ESP32 Applications&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md89',1,'']]],
  ['esp32_20esp_20idf_14',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md116',1,'']]],
  ['esp32_20examples_15',['Using ESP-IDF (ESP32 Examples)',['../md_docs_2installation.html#autotoc_md100',1,'']]],
  ['example_16',['Minimal Example',['../md_docs_2quickstart.html#autotoc_md129',1,'']]],
  ['example_201_3a_20basic_20servo_20control_17',['Example 1: Basic Servo Control',['../md_docs_2examples.html#autotoc_md58',1,'']]],
  ['example_203_3a_20multiple_20channels_18',['Example 3: Multiple Channels',['../md_docs_2examples.html#autotoc_md61',1,'']]],
  ['example_205_3a_20bulk_20channel_20update_19',['Example 5: Bulk Channel Update',['../md_docs_2examples.html#autotoc_md63',1,'']]],
  ['example_20wiring_20diagram_20',['Example Wiring Diagram',['../md_docs_2hardware__setup.html#autotoc_md79',1,'']]],
  ['examples_21',['Examples',['../index.html#autotoc_md7',1,'📊 Examples'],['../md_docs_2examples.html',1,'Examples'],['../md_docs_2examples.html#autotoc_md65',1,'Running the Examples'],['../md_docs_2platform__integration.html#autotoc_md115',1,'Step 2: Platform-Specific Examples'],['../md_docs_2installation.html#autotoc_md100',1,'Using ESP-IDF (ESP32 Examples)']]],
  ['examples_2emd_22',['examples.md',['../examples_8md.html',1,'']]],
  ['expected_20output_23',['Expected Output',['../md_docs_2examples.html#autotoc_md60',1,'Expected Output'],['../md_docs_2quickstart.html#autotoc_md137',1,'Expected Output']]],
  ['explanation_24',['Explanation',['../md_docs_2examples.html#autotoc_md59',1,'Explanation'],['../md_docs_2examples.html#autotoc_md62',1,'Explanation'],['../md_docs_2examples.html#autotoc_md64',1,'Explanation'],['../md_docs_2quickstart.html#autotoc_md130',1,'Step-by-Step Explanation']]]
];
