var searchData=
[
  ['t_20forget_20the_20template_20parameter_0',['❌ Don&apos;t Forget the Template Parameter',['../md_docs_2platform__integration.html#autotoc_md114',1,'']]],
  ['t_20use_20virtual_20functions_1',['❌ Don&apos;t Use Virtual Functions',['../md_docs_2platform__integration.html#autotoc_md112',1,'']]],
  ['table_20of_20contents_2',['📚 Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['template_20parameter_3',['Template Parameter',['../md_docs_2platform__integration.html#autotoc_md115',1,'✅ Correct Template Parameter'],['../md_docs_2platform__integration.html#autotoc_md114',1,'❌ Don&apos;t Forget the Template Parameter']]],
  ['template_20pattern_4',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md96',1,'']]],
  ['testing_20your_20implementation_5',['Testing Your Implementation',['../md_docs_2platform__integration.html#autotoc_md117',1,'']]],
  ['tests_6',['Running Unit Tests',['../md_docs_2installation.html#autotoc_md92',1,'']]],
  ['the_20difference_20between_20setpwm_20and_20setduty_7',['Q: What&apos;s the difference between SetPwm() and SetDuty()?',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['the_20examples_8',['Running the Examples',['../md_docs_2examples.html#autotoc_md57',1,'']]],
  ['the_20header_9',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md123',1,'']]],
  ['the_20i2c_20interface_10',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md124',1,'']]],
  ['the_20library_11',['Building the Library',['../md_docs_2installation.html#autotoc_md88',1,'']]],
  ['the_20oe_20output_20enable_20pin_12',['Q: How do I control the OE (Output Enable) pin?',['../md_docs_2troubleshooting.html#autotoc_md146',1,'']]],
  ['the_20source_13',['Obtaining the Source',['../md_docs_2installation.html#autotoc_md85',1,'']]],
  ['the_20template_20parameter_14',['❌ Don&apos;t Forget the Template Parameter',['../md_docs_2platform__integration.html#autotoc_md114',1,'']]],
  ['time_20polymorphism_20strong_15',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md99',1,'']]],
  ['to_20call_20setpwmfreq_20before_20setting_20channels_16',['Q: Why do I need to call SetPwmFreq() before setting channels?',['../md_docs_2troubleshooting.html#autotoc_md141',1,'']]],
  ['troubleshooting_17',['Troubleshooting',['../md_docs_2troubleshooting.html',1,'Troubleshooting'],['../md_docs_2quickstart.html#autotoc_md130',1,'Troubleshooting']]],
  ['troubleshooting_20strong_18',['&lt;strong&gt;Troubleshooting&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md81',1,'']]],
  ['troubleshooting_2emd_19',['troubleshooting.md',['../troubleshooting_8md.html',1,'']]],
  ['tt_20i2cinterface_20derived_20tt_20crtp_20',['&lt;tt&gt;I2cInterface\&lt;Derived\&gt;&lt;/tt&gt; (CRTP)',['../md_docs_2api__reference.html#autotoc_md27',1,'']]],
  ['tt_20pca9685_20i2ctype_20tt_21',['&lt;tt&gt;PCA9685\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md14',1,'']]],
  ['tt_20reset_20tt_20returns_20false_22',['Error: Initialization Fails (&lt;tt&gt;Reset()&lt;/tt&gt; returns false)',['../md_docs_2troubleshooting.html#autotoc_md134',1,'']]],
  ['type_20safety_23',['4. **Type Safety**',['../md_docs_2platform__integration.html#autotoc_md101',1,'']]],
  ['types_24',['Types',['../md_docs_2api__reference.html#autotoc_md23',1,'']]]
];
