var searchData=
[
  ['i_20change_20frequency_20after_20setting_20channels_0',['Q: Can I change frequency after setting channels?',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['i_20control_20the_20oe_20output_20enable_20pin_1',['Q: How do I control the OE (Output Enable) pin?',['../md_docs_2troubleshooting.html#autotoc_md147',1,'']]],
  ['i_20need_20to_20call_20setpwmfreq_20before_20setting_20channels_2',['Q: Why do I need to call SetPwmFreq() before setting channels?',['../md_docs_2troubleshooting.html#autotoc_md142',1,'']]],
  ['i_20use_20multiple_20pca9685_20devices_3',['Q: Can I use multiple PCA9685 devices?',['../md_docs_2troubleshooting.html#autotoc_md145',1,'']]],
  ['i2c_20address_20configuration_4',['I2C Address Configuration',['../md_docs_2configuration.html#autotoc_md30',1,'']]],
  ['i2c_20bus_20configuration_5',['I2C Bus Configuration',['../md_docs_2hardware__setup.html#autotoc_md70',1,'']]],
  ['i2c_20configuration_6',['I2C Configuration',['../md_docs_2hardware__setup.html#autotoc_md68',1,'']]],
  ['i2c_20connections_7',['Basic I2C Connections',['../md_docs_2hardware__setup.html#autotoc_md64',1,'']]],
  ['i2c_20interface_8',['I2C Interface',['../md_docs_2api__reference.html#autotoc_md27',1,'I2C Interface'],['../md_docs_2quickstart.html#autotoc_md125',1,'Step 2: Implement the I2C Interface']]],
  ['i2cinterface_20derived_20tt_20crtp_9',['&lt;tt&gt;I2cInterface\&lt;Derived\&gt;&lt;/tt&gt; (CRTP)',['../md_docs_2api__reference.html#autotoc_md28',1,'']]],
  ['i2ctype_20tt_10',['&lt;tt&gt;PCA9685\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md14',1,'']]],
  ['idf_11',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md109',1,'']]],
  ['idf_20esp32_20examples_12',['Using ESP-IDF (ESP32 Examples)',['../md_docs_2installation.html#autotoc_md93',1,'']]],
  ['implement_20the_20i2c_20interface_13',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md125',1,'']]],
  ['implementation_14',['Implementation',['../md_docs_2platform__integration.html#autotoc_md114',1,'✅ Correct CRTP Implementation'],['../md_docs_2platform__integration.html#autotoc_md118',1,'Testing Your Implementation']]],
  ['implementation_20class_15',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md107',1,'']]],
  ['implementation_20steps_16',['Implementation Steps',['../md_docs_2platform__integration.html#autotoc_md106',1,'']]],
  ['include_20path_17',['As Part of Your Project (Include Path)',['../md_docs_2installation.html#autotoc_md91',1,'']]],
  ['include_20the_20header_18',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md124',1,'']]],
  ['increment_19',['Auto-Increment',['../md_docs_2configuration.html#autotoc_md42',1,'']]],
  ['index_2emd_20',['index.md',['../index_8md.html',1,'']]],
  ['individual_20channel_20control_21',['Individual Channel Control',['../md_docs_2configuration.html#autotoc_md36',1,'']]],
  ['initialization_22',['Initialization',['../md_docs_2api__reference.html#autotoc_md16',1,'']]],
  ['initialization_20fails_20tt_20reset_20tt_20returns_20false_23',['Error: Initialization Fails (&lt;tt&gt;Reset()&lt;/tt&gt; returns false)',['../md_docs_2troubleshooting.html#autotoc_md135',1,'']]],
  ['initialization_20sequence_24',['Initialization Sequence',['../md_docs_2configuration.html#autotoc_md44',1,'']]],
  ['initialize_25',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md127',1,'']]],
  ['installation_26',['Installation',['../index.html#autotoc_md5',1,'🔧 Installation'],['../md_docs_2installation.html',1,'Installation']]],
  ['installation_2emd_27',['installation.md',['../installation_8md.html',1,'']]],
  ['instance_28',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md126',1,'']]],
  ['instead_20of_20virtual_20functions_29',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md98',1,'']]],
  ['integration_20guide_30',['Platform Integration Guide',['../md_docs_2platform__integration.html',1,'']]],
  ['integration_20strong_31',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md80',1,'']]],
  ['interface_32',['Interface',['../md_docs_2api__reference.html#autotoc_md27',1,'I2C Interface'],['../md_docs_2quickstart.html#autotoc_md125',1,'Step 2: Implement the I2C Interface']]],
  ['interface_20definition_33',['Interface Definition',['../md_docs_2platform__integration.html#autotoc_md105',1,'']]],
  ['issues_34',['Hardware Issues',['../md_docs_2troubleshooting.html#autotoc_md137',1,'']]]
];
