var searchData=
[
  ['i_20change_20frequency_20after_20setting_20channels_0',['Q: Can I change frequency after setting channels?',['../md_docs_2troubleshooting.html#autotoc_md151',1,'']]],
  ['i_20control_20the_20oe_20output_20enable_20pin_1',['Q: How do I control the OE (Output Enable) pin?',['../md_docs_2troubleshooting.html#autotoc_md155',1,'']]],
  ['i_20need_20to_20call_20setpwmfreq_20before_20setting_20channels_2',['Q: Why do I need to call SetPwmFreq() before setting channels?',['../md_docs_2troubleshooting.html#autotoc_md150',1,'']]],
  ['i_20use_20multiple_20pca9685_20devices_3',['Q: Can I use multiple PCA9685 devices?',['../md_docs_2troubleshooting.html#autotoc_md153',1,'']]],
  ['i2c_20address_20configuration_4',['I2C Address Configuration',['../md_docs_2configuration.html#autotoc_md38',1,'']]],
  ['i2c_20bus_20configuration_5',['I2C Bus Configuration',['../md_docs_2hardware__setup.html#autotoc_md78',1,'']]],
  ['i2c_20configuration_6',['I2C Configuration',['../md_docs_2hardware__setup.html#autotoc_md76',1,'']]],
  ['i2c_20connections_7',['Basic I2C Connections',['../md_docs_2hardware__setup.html#autotoc_md72',1,'']]],
  ['i2c_20interface_8',['I2C Interface',['../md_docs_2api__reference.html#autotoc_md28',1,'I2C Interface'],['../md_docs_2quickstart.html#autotoc_md133',1,'Step 2: Implement the I2C Interface']]],
  ['i2cinterface_20derived_20tt_20crtp_9',['&lt;tt&gt;I2cInterface\&lt;Derived\&gt;&lt;/tt&gt; (CRTP)',['../md_docs_2api__reference.html#autotoc_md29',1,'']]],
  ['i2ctype_20tt_10',['&lt;tt&gt;PCA9685\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md15',1,'']]],
  ['idf_11',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md117',1,'']]],
  ['idf_20esp32_20examples_12',['Using ESP-IDF (ESP32 Examples)',['../md_docs_2installation.html#autotoc_md101',1,'']]],
  ['idf_20integration_13',['ESP-IDF Integration',['../md_docs_2cmake__integration.html#autotoc_md31',1,'']]],
  ['if_20needed_14',['2. Override the Driver Root (if needed)',['../md_docs_2cmake__integration.html#autotoc_md33',1,'']]],
  ['implement_20the_20i2c_20interface_15',['Step 2: Implement the I2C Interface',['../md_docs_2quickstart.html#autotoc_md133',1,'']]],
  ['implementation_16',['Implementation',['../md_docs_2platform__integration.html#autotoc_md122',1,'✅ Correct CRTP Implementation'],['../md_docs_2platform__integration.html#autotoc_md126',1,'Testing Your Implementation']]],
  ['implementation_20class_17',['Step 1: Create Your Implementation Class',['../md_docs_2platform__integration.html#autotoc_md115',1,'']]],
  ['implementation_20steps_18',['Implementation Steps',['../md_docs_2platform__integration.html#autotoc_md114',1,'']]],
  ['include_20and_20use_19',['4. Include and Use',['../md_docs_2cmake__integration.html#autotoc_md35',1,'']]],
  ['include_20path_20',['As Part of Your Project (Include Path)',['../md_docs_2installation.html#autotoc_md99',1,'']]],
  ['include_20the_20header_21',['Step 1: Include the Header',['../md_docs_2quickstart.html#autotoc_md132',1,'']]],
  ['increment_22',['Auto-Increment',['../md_docs_2configuration.html#autotoc_md50',1,'']]],
  ['index_2emd_23',['index.md',['../index_8md.html',1,'']]],
  ['individual_20channel_20control_24',['Individual Channel Control',['../md_docs_2configuration.html#autotoc_md44',1,'']]],
  ['initialization_25',['Initialization',['../md_docs_2api__reference.html#autotoc_md17',1,'']]],
  ['initialization_20fails_20tt_20reset_20tt_20returns_20false_26',['Error: Initialization Fails (&lt;tt&gt;Reset()&lt;/tt&gt; returns false)',['../md_docs_2troubleshooting.html#autotoc_md143',1,'']]],
  ['initialization_20sequence_27',['Initialization Sequence',['../md_docs_2configuration.html#autotoc_md52',1,'']]],
  ['initialize_28',['Step 4: Initialize',['../md_docs_2quickstart.html#autotoc_md135',1,'']]],
  ['installation_29',['Installation',['../index.html#autotoc_md5',1,'🔧 Installation'],['../md_docs_2installation.html',1,'Installation']]],
  ['installation_2emd_30',['installation.md',['../installation_8md.html',1,'']]],
  ['instance_31',['Step 3: Create Driver Instance',['../md_docs_2quickstart.html#autotoc_md134',1,'']]],
  ['instead_20of_20virtual_20functions_32',['Why CRTP Instead of Virtual Functions?',['../md_docs_2platform__integration.html#autotoc_md106',1,'']]],
  ['integration_33',['ESP-IDF Integration',['../md_docs_2cmake__integration.html#autotoc_md31',1,'']]],
  ['integration_20guide_34',['Integration Guide',['../md_docs_2cmake__integration.html',1,'PCA9685 — CMake Integration Guide'],['../md_docs_2platform__integration.html',1,'Platform Integration Guide']]],
  ['integration_20strong_35',['&lt;strong&gt;Integration&lt;/strong&gt;',['../md_docs_2index.html#autotoc_md88',1,'']]],
  ['interface_36',['Interface',['../md_docs_2api__reference.html#autotoc_md28',1,'I2C Interface'],['../md_docs_2quickstart.html#autotoc_md133',1,'Step 2: Implement the I2C Interface']]],
  ['interface_20definition_37',['Interface Definition',['../md_docs_2platform__integration.html#autotoc_md113',1,'']]],
  ['issues_38',['Hardware Issues',['../md_docs_2troubleshooting.html#autotoc_md145',1,'']]]
];
