var searchData=
[
  ['parameter_0',['Parameter',['../md_docs_2platform__integration.html#autotoc_md123',1,'✅ Correct Template Parameter'],['../md_docs_2platform__integration.html#autotoc_md122',1,'❌ Don&apos;t Forget the Template Parameter']]],
  ['part_20of_20your_20project_20include_20path_1',['As Part of Your Project (Include Path)',['../md_docs_2installation.html#autotoc_md98',1,'']]],
  ['path_2',['As Part of Your Project (Include Path)',['../md_docs_2installation.html#autotoc_md98',1,'']]],
  ['pattern_3',['Understanding CRTP (Curiously Recurring Template Pattern)',['../md_docs_2platform__integration.html#autotoc_md104',1,'']]],
  ['pca9685_4',['Single PCA9685',['../md_docs_2hardware__setup.html#autotoc_md80',1,'']]],
  ['pca9685_20—_20cmake_20integration_20guide_5',['PCA9685 — CMake Integration Guide',['../md_docs_2cmake__integration.html',1,'']]],
  ['pca9685_20devices_6',['Q: Can I use multiple PCA9685 devices?',['../md_docs_2troubleshooting.html#autotoc_md152',1,'']]],
  ['pca9685_20devices_20daisy_20chain_7',['Multiple PCA9685 Devices (Daisy Chain)',['../md_docs_2hardware__setup.html#autotoc_md81',1,'']]],
  ['pca9685_20documentation_8',['HF-PCA9685 Documentation',['../md_docs_2index.html',1,'']]],
  ['pca9685_20driver_9',['HF-PCA9685 Driver',['../index.html',1,'']]],
  ['pca9685_20i2ctype_20tt_10',['&lt;tt&gt;PCA9685\&lt;I2cType\&gt;&lt;/tt&gt;',['../md_docs_2api__reference.html#autotoc_md14',1,'']]],
  ['pca9685_2eipp_11',['pca9685.ipp',['../pca9685_8ipp.html',1,'']]],
  ['pca9685_5fimpl_12',['PCA9685_IMPL',['../pca9685_8ipp.html#a65030673b1f4c161d7148fd2f5591a7a',1,'pca9685.ipp']]],
  ['performance_20comparison_13',['Performance Comparison',['../md_docs_2platform__integration.html#autotoc_md111',1,'']]],
  ['physical_20layout_20recommendations_14',['Physical Layout Recommendations',['../md_docs_2hardware__setup.html#autotoc_md78',1,'']]],
  ['pin_15',['Pin',['../md_docs_2configuration.html#autotoc_md47',1,'Output Enable (OE) Pin'],['../md_docs_2hardware__setup.html#autotoc_md82',1,'Output Enable (OE) Pin'],['../md_docs_2troubleshooting.html#autotoc_md154',1,'Q: How do I control the OE (Output Enable) pin?']]],
  ['pin_20connections_16',['Pin Connections',['../md_docs_2hardware__setup.html#autotoc_md70',1,'']]],
  ['pin_20descriptions_17',['Pin Descriptions',['../md_docs_2hardware__setup.html#autotoc_md72',1,'']]],
  ['pitfalls_18',['Common Pitfalls',['../md_docs_2platform__integration.html#autotoc_md119',1,'']]],
  ['platform_20integration_20guide_19',['Platform Integration Guide',['../md_docs_2platform__integration.html',1,'']]],
  ['platform_20specific_20examples_20',['Step 2: Platform-Specific Examples',['../md_docs_2platform__integration.html#autotoc_md115',1,'']]],
  ['platform_5fintegration_2emd_21',['platform_integration.md',['../platform__integration_8md.html',1,'']]],
  ['platforms_22',['Other Platforms',['../md_docs_2examples.html#autotoc_md67',1,'']]],
  ['polymorphism_20strong_23',['2. &lt;strong&gt;Compile-Time Polymorphism&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md107',1,'']]],
  ['power_20management_24',['Power Management',['../md_docs_2api__reference.html#autotoc_md19',1,'']]],
  ['power_20requirements_25',['Power Requirements',['../md_docs_2hardware__setup.html#autotoc_md74',1,'']]],
  ['prerequisites_26',['Prerequisites',['../md_docs_2installation.html#autotoc_md93',1,'Prerequisites'],['../md_docs_2quickstart.html#autotoc_md128',1,'Prerequisites']]],
  ['project_20include_20path_27',['As Part of Your Project (Include Path)',['../md_docs_2installation.html#autotoc_md98',1,'']]],
  ['pwm_20control_28',['PWM Control',['../md_docs_2api__reference.html#autotoc_md18',1,'']]],
  ['pwm_20frequency_29',['Step 5: Set PWM Frequency',['../md_docs_2quickstart.html#autotoc_md135',1,'']]],
  ['pwm_20frequency_20configuration_30',['PWM Frequency Configuration',['../md_docs_2configuration.html#autotoc_md38',1,'']]]
];
