var searchData=
[
  ['efficiency_20strong_0',['3. &lt;strong&gt;Memory Efficiency&lt;/strong&gt;',['../md_docs_2platform__integration.html#autotoc_md100',1,'']]],
  ['enable_20oe_20pin_1',['Enable OE Pin',['../md_docs_2configuration.html#autotoc_md39',1,'Output Enable (OE) Pin'],['../md_docs_2hardware__setup.html#autotoc_md74',1,'Output Enable (OE) Pin']]],
  ['enable_20pin_2',['Q: How do I control the OE (Output Enable) pin?',['../md_docs_2troubleshooting.html#autotoc_md146',1,'']]],
  ['enumerations_3',['Enumerations',['../md_docs_2api__reference.html#autotoc_md24',1,'']]],
  ['error_20handling_4',['Error Handling',['../md_docs_2api__reference.html#autotoc_md21',1,'']]],
  ['error_20messages_5',['Common Error Messages',['../md_docs_2troubleshooting.html#autotoc_md133',1,'']]],
  ['error_3a_20channel_20out_20of_20range_6',['Error: Channel Out of Range',['../md_docs_2troubleshooting.html#autotoc_md135',1,'']]],
  ['error_3a_20initialization_20fails_20tt_20reset_20tt_20returns_20false_7',['Error: Initialization Fails (&lt;tt&gt;Reset()&lt;/tt&gt; returns false)',['../md_docs_2troubleshooting.html#autotoc_md134',1,'']]],
  ['errors_8',['Runtime Errors',['../md_docs_2troubleshooting.html#autotoc_md139',1,'']]],
  ['esp_20idf_9',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['esp_20idf_20component_10',['Using ESP-IDF Component',['../md_docs_2installation.html#autotoc_md91',1,'']]],
  ['esp32_11',['ESP32',['../md_docs_2examples.html#autotoc_md58',1,'']]],
  ['esp32_20esp_20idf_12',['ESP32 (ESP-IDF)',['../md_docs_2platform__integration.html#autotoc_md108',1,'']]],
  ['example_13',['Minimal Example',['../md_docs_2quickstart.html#autotoc_md121',1,'']]],
  ['example_201_3a_20basic_20servo_20control_14',['Example 1: Basic Servo Control',['../md_docs_2examples.html#autotoc_md50',1,'']]],
  ['example_203_3a_20multiple_20channels_15',['Example 3: Multiple Channels',['../md_docs_2examples.html#autotoc_md53',1,'']]],
  ['example_205_3a_20bulk_20channel_20update_16',['Example 5: Bulk Channel Update',['../md_docs_2examples.html#autotoc_md55',1,'']]],
  ['example_20wiring_20diagram_17',['Example Wiring Diagram',['../md_docs_2hardware__setup.html#autotoc_md71',1,'']]],
  ['examples_18',['Examples',['../index.html#autotoc_md7',1,'📊 Examples'],['../md_docs_2examples.html',1,'Examples'],['../md_docs_2examples.html#autotoc_md57',1,'Running the Examples'],['../md_docs_2platform__integration.html#autotoc_md107',1,'Step 2: Platform-Specific Examples']]],
  ['examples_2emd_19',['examples.md',['../examples_8md.html',1,'']]],
  ['expected_20output_20',['Expected Output',['../md_docs_2examples.html#autotoc_md52',1,'Expected Output'],['../md_docs_2quickstart.html#autotoc_md129',1,'Expected Output']]],
  ['explanation_21',['Explanation',['../md_docs_2examples.html#autotoc_md51',1,'Explanation'],['../md_docs_2examples.html#autotoc_md54',1,'Explanation'],['../md_docs_2examples.html#autotoc_md56',1,'Explanation'],['../md_docs_2quickstart.html#autotoc_md122',1,'Step-by-Step Explanation']]]
];
